CREATE TABLE shared_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    content_id BIGINT NOT NULL,
    share_token VARCHAR(80) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    tags VARCHAR(500),
    download_count BIGINT NOT NULL DEFAULT 0,
    source_share_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT uk_shared_contents_share_token UNIQUE (share_token),
    CONSTRAINT fk_shared_contents_source FOREIGN KEY (source_share_id) REFERENCES shared_contents(id)
);

CREATE INDEX idx_shared_contents_owner_id ON shared_contents(owner_id);
CREATE INDEX idx_shared_contents_content_type ON shared_contents(content_type);
CREATE INDEX idx_shared_contents_created_at ON shared_contents(created_at);
CREATE INDEX idx_shared_contents_title ON shared_contents(title);
