spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:engagement;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    io.synapse: DEBUG
