CREATE TABLE user_profiles_gamification (
    user_id BIGINT PRIMARY KEY,
    total_xp INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE xp_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    xp_amount INTEGER NOT NULL,
    source_id VARCHAR(100) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    event_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_xp_events_profile FOREIGN KEY (user_id) REFERENCES user_profiles_gamification(user_id),
    CONSTRAINT uk_xp_events_event_id UNIQUE (event_id),
    CONSTRAINT uk_xp_events_user_event_source UNIQUE (user_id, event_type, source_id)
);

CREATE INDEX idx_xp_events_user_id ON xp_events(user_id);
CREATE INDEX idx_xp_events_created_at ON xp_events(created_at);
