CREATE TABLE badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    icon_url VARCHAR(500),
    condition_type VARCHAR(30) NOT NULL,
    condition_value INTEGER NOT NULL,
    CONSTRAINT uk_badges_code UNIQUE (code)
);

CREATE TABLE user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    badge_id BIGINT NOT NULL,
    earned_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_badges_badge FOREIGN KEY (badge_id) REFERENCES badges(id),
    CONSTRAINT uk_user_badges_user_badge UNIQUE (user_id, badge_id)
);

CREATE INDEX idx_user_badges_user_id ON user_badges(user_id);

CREATE TABLE user_streaks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    current_streak INTEGER NOT NULL DEFAULT 0,
    longest_streak INTEGER NOT NULL DEFAULT 0,
    last_activity_date DATE,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_streaks_user_id UNIQUE (user_id)
);

CREATE INDEX idx_user_streaks_user_id ON user_streaks(user_id);

INSERT INTO badges (code, name, description, icon_url, condition_type, condition_value)
VALUES
    ('FIRST_XP', 'First XP', 'Earn XP for the first time', NULL, 'TOTAL_XP', 1),
    ('LEVEL_2', 'Level 2', 'Reach level 2', NULL, 'LEVEL', 2),
    ('STREAK_3', '3 Day Streak', 'Keep a 3 day activity streak', NULL, 'STREAK', 3);
